.Dd $Mdocdate: June 04 2022 $
.Dt REDO-OOD 1
.Os
.Sh NAME
.Nm redo-ood
.Nd write a list of out-of-date targets to the standard output
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility descends recursively through the database
.Pq .redo ,
writing every out-of-date target to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr redo-sources 1 ,
.Xr redo-targets 1
