.Dd $Mdocdate: Semptember 22 2023 $
.Dt REDO-OOD 1
.Os
.Sh NAME
.Nm redo-ood
.Nd write a list of out-of-date targets to the standard output
.Sh SYNOPSIS
.Nm
.Op Ar path
.Sh DESCRIPTION
The
.Nm
utility lists all out-of-date targets that depends on the source
.Ar path .
If
.Ar path
is a directory,
.Nm
recursively lists all out-of-date targets in that directory.
If no
.Ar path
is specified,
.Nm
recursively descends through the database
.Pq .redo
writing every out-of-date target to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr redo-sources 1 ,
.Xr redo-targets 1
