.Dd $Mdocdate: September 22 2023 $
.Dt REDO-TARGETS 1
.Os
.Sh NAME
.Nm redo-targets
.Nd write a list of targets to the standard output
.Sh SYNOPSIS
.Nm
.Op Ar path
.Sh DESCRIPTION
The
.Nm
utility lists all targets that depends on the source
.Ar path .
If
.Ar path
is a directory,
.Nm
recursively lists all targets in that directory.
If no
.Ar path
is specified,
.Nm
recursively descends through the database
.Pq .redo
writing every target to the standard output.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr redo-ood 1 ,
.Xr redo-sources 1
